version: "3.9"

services:
  traefik-v3.0:
    image: "traefik:v3.0"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8000"
      - "--serverstransport.maxidleconnsperhost=100000"
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  traefik-v2.9:
    image: "traefik:v2.9"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8002"
      - "--serverstransport.maxidleconnsperhost=100000"
    ports:
      - "8002:8002"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nginx:
    image: nginx:alpine
    ports:
      - "8001:8001"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./go-benchmark.conf:/etc/nginx/conf.d/go-benchmark.conf:ro"

  go-benchmark-1:
    image: "containous/whoami"
    ports:
      - "9000:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-benchmark.rule=Host(`benchmark.traefik`)"
      - "traefik.http.services.go-benchmark.loadbalancer.server.port=80"

  go-benchmark-2:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-benchmark.rule=Host(`benchmark.traefik`)"
      - "traefik.http.services.go-benchmark.loadbalancer.server.port=80"

  go-benchmark-3:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-benchmark.rule=Host(`benchmark.traefik`)"
      - "traefik.http.services.go-benchmark.loadbalancer.server.port=80"

  go-benchmark-4:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-benchmark.rule=Host(`benchmark.traefik`)"
      - "traefik.http.services.go-benchmark.loadbalancer.server.port=80"